language: node_js
sudo: required
services:
  - docker

before_install:
  - docker build -t tvivektripathi79/docker-react -f Dockerfile.dev .

script:
  - docker run tvivektripathi79/docker-react npm run test -- --coverage