version: '3'
services: 
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes: 
            - /home/advik/nodeapp/frontend/node_modules
            - .:/home/advik/nodeapp/frontend

    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /home/advik/nodeapp/frontend/node_modules
            - .:/home/advik/nodeapp/frontend        
        command: ["npm", "run", "test"]